title: Ben Maxwell - Portfolio
author: Ben Maxwell
email: bmax16634@gmail.com
description: Ben Maxwell - Computer Vision, iOS, AI, Machine Learning, Artificial Intelligence, Swit, Python, Objective-C, Deep Learning, Self-Driving Cars
url: "https://https://bmax16634.github.io/"
twitter_username: gsurma
github_username:  gsurma
google_analytics: UA-110543961-1

theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
